spring:
  profiles:
    active: dev
---
server:
  port: 7001
#环境配置
spring:
  profiles: dev
  application:
    name: springcloud-config-eureka

#eureka配置
eureka:
  instance:
    hostname: eureka7001.com #表示eureka服务器的实例名称
  client:
    register-with-eureka: false #表示是否向eureka注册自己，因为这个是服务器所以无需注册
    fetch-registry: false #如果为false表示自己就是注册中心
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #这个是后续服务注册须填写的注册中心的的url地址

---

server:
  port: 7001
#环境配置
spring:
  profiles: test
  application:
    name: springcloud-config-eureka
#eureka配置
eureka:
  instance:
    hostname: eureka7001.com #表示eureka服务器的实例名称
  client:
    register-with-eureka: false #表示是否向eureka注册自己，因为这个是服务器所以无需注册
    fetch-registry: false #如果为false表示自己就是注册中心
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #这个是后续服务注册须填写的注册中心的的url地址

